name: Release instructions

on:
  push:
    tags:
      - "v*"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: ubuntu-20.04

  steps:
    - name: Build project with setuptool
        run: |
          python3 -m pip install .[]
          python3 setup.py bdist_wheel

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            dist/*.whl