name: Release instructions

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      
      - name: Build project with setuptool
        run: |
          python -m pip install .
          python setup.py bdist_wheel

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.AUTH_TOKEN }}"
          prerelease: false
          files: |
            dist/*.whl
